name: "krusty"

services:
  # Uncomment the following section to enable Redict
  # redict:
  #   image: registry.redict.io/redict:7-debian
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redict_data:/data

  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

  tempo:
    image: grafana/tempo:latest
    restart: unless-stopped
    ports:
      - 3200:3200
      - 4317:4317
      - 4318:4318
    volumes:
      - ./tempo/config.yaml:/etc/tempo/local-config.yaml
      - tempo_data:/var/tempo
    command: -config.file=/etc/tempo/local-config.yaml

volumes:
  redict_data:
  loki_data:
  grafana_data:
  tempo_data:
