apiVersion: v1
kind: ConfigMap
metadata:
  name: krusty-config
data:
  config.json: |
    {
      "queue_id": "",
      "filters": [
        {
          "channel_ids": [],
          "filters": {
            "include_npc": false,
            "characters": {
              "includes": [],
              "excludes": []
            },
            "corps": {
              "includes": [],
              "excludes": []
            },
            "alliances": {
              "includes": [],
              "excludes": []
            }
          }
        }
      ]
    }
