server:
  http_listen_port: 3200
  grpc_listen_port: 3300

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: "0.0.0.0:4318"

compactor:
  compaction:
    block_retention: 48h # configure total trace retention here

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces
    wal:
      path: /tmp/tempo/wal
